-------------------------------------------------------------------------------
-- RETAIL TRANSFORM DEMO: Grants
-- Run as: SECURITYADMIN
-------------------------------------------------------------------------------

USE ROLE SECURITYADMIN;

-- Database-level grants
GRANT OWNERSHIP ON DATABASE RETAIL_TRANSFORM_DEMO TO ROLE DEMO_ADMIN;
GRANT USAGE ON DATABASE RETAIL_TRANSFORM_DEMO TO ROLE DEMO_ENGINEER;
GRANT USAGE ON DATABASE RETAIL_TRANSFORM_DEMO TO ROLE DEMO_ANALYST;

-- Schema-level grants: ENGINEER gets full CRUD on all schemas
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.RAW     TO ROLE DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.BRONZE  TO ROLE DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.STAGING TO ROLE DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.REF     TO ROLE DEMO_ENGINEER;

-- TRANSFORMER gets write on SILVER/GOLD (dbt, dynamic tables)
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.SILVER TO ROLE DEMO_TRANSFORMER;
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.GOLD   TO ROLE DEMO_TRANSFORMER;
GRANT USAGE ON SCHEMA RETAIL_TRANSFORM_DEMO.RAW             TO ROLE DEMO_TRANSFORMER;
GRANT USAGE ON SCHEMA RETAIL_TRANSFORM_DEMO.BRONZE          TO ROLE DEMO_TRANSFORMER;
GRANT USAGE ON SCHEMA RETAIL_TRANSFORM_DEMO.REF             TO ROLE DEMO_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.BRONZE TO ROLE DEMO_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.REF    TO ROLE DEMO_TRANSFORMER;

-- ANALYST gets read on SILVER and GOLD only
GRANT USAGE ON SCHEMA RETAIL_TRANSFORM_DEMO.SILVER TO ROLE DEMO_ANALYST;
GRANT USAGE ON SCHEMA RETAIL_TRANSFORM_DEMO.GOLD   TO ROLE DEMO_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.SILVER TO ROLE DEMO_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.GOLD   TO ROLE DEMO_ANALYST;
GRANT SELECT ON ALL DYNAMIC TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.GOLD TO ROLE DEMO_ANALYST;

-- Future grants so new objects inherit permissions
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.SILVER TO ROLE DEMO_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.GOLD   TO ROLE DEMO_ANALYST;
GRANT SELECT ON FUTURE DYNAMIC TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.GOLD TO ROLE DEMO_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.BRONZE TO ROLE DEMO_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA RETAIL_TRANSFORM_DEMO.REF    TO ROLE DEMO_TRANSFORMER;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE DEMO_ETL_WH       TO ROLE DEMO_ENGINEER;
GRANT USAGE ON WAREHOUSE DEMO_TRANSFORM_WH TO ROLE DEMO_TRANSFORMER;
GRANT USAGE ON WAREHOUSE DEMO_ANALYTICS_WH TO ROLE DEMO_ANALYST;
GRANT USAGE ON WAREHOUSE DEMO_ANALYTICS_WH TO ROLE DEMO_TRANSFORMER;

-- Task execution privilege
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DEMO_ENGINEER;
