-------------------------------------------------------------------------------
-- RETAIL TRANSFORM DEMO: Grants
-- Run as: SECURITYADMIN
-------------------------------------------------------------------------------

USE ROLE SECURITYADMIN;

-- Database-level grants
GRANT OWNERSHIP ON DATABASE RETAIL_TRANSFORM_DEMO TO ROLE DEMO_ADMIN;
GRANT USAGE ON DATABASE RETAIL_TRANSFORM_DEMO TO ROLE DEMO_ENGINEER;

-- Schema-level grants: ENGINEER gets full privileges on all schemas
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.RAW     TO ROLE DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.BRONZE  TO ROLE DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.STAGING TO ROLE DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.REF     TO ROLE DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.SILVER  TO ROLE DEMO_ENGINEER;
GRANT ALL PRIVILEGES ON SCHEMA RETAIL_TRANSFORM_DEMO.GOLD    TO ROLE DEMO_ENGINEER;

-- Warehouse grants
GRANT USAGE ON WAREHOUSE DEMO_ETL_WH       TO ROLE DEMO_ENGINEER;
GRANT USAGE ON WAREHOUSE DEMO_TRANSFORM_WH TO ROLE DEMO_ENGINEER;
GRANT USAGE ON WAREHOUSE DEMO_ANALYTICS_WH TO ROLE DEMO_ENGINEER;

-- Task execution privilege
GRANT EXECUTE TASK ON ACCOUNT TO ROLE DEMO_ENGINEER;
